version: '3.9'

networks:
  open:
    driver: bridge
  app:
services:
  selenium:
    hostname: selenium
    ports:
      - "4444:4444"
    image: selenium/standalone-chrome
    networks:
      - app
  scraper:
    hostname: scraper
    ports:
      - "8080:8080"
    image: node:14.19.0
    build:
        dockerfile: ./DockerFile
        context: ./
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=google-auth.json
    depends_on:
      - selenium
    networks:
      - open
      - app
